// Extracted matches from Fiverr Profile
// Deduplicated and filtered for best reviews
window.fiverrReviewsData = [
  {
    "client": "fridarays",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "i really appreciate working with you. I definitely recommend your service",
    "highlight": "i really appreciate working with you. I definitely...",
    "image": "fiver.svg",
    "country": "United Kingdom",
    "date": "3 months ago"
  },
  {
    "client": "jayskaines",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "Very Talented. Can't fault his work. much appreciated",
    "highlight": "Very Talented. Can't fault his work. much appreciated...",
    "image": "fiver.svg",
    "country": "Australia",
    "date": "4 years ago"
  },
  {
    "client": "bishalagarwall",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "I recently had the pleasure of working with someone who is an absolute genius in their field. Their level of understanding and expertise truly impressed me. Not only were they incredibly knowledgeable, but they were also very sincere in their approach. It was clear that they genuinely cared about their... <span class=\"expand-description-wrapper\"><span class=\"expand-button\"><button class=\"_05cff4 _15fd3a co-white expand-description expand-button-text bg-co-green-700\" data-impression-collected=\"true\"><span class=\"text-normal\"><u>See more</u></span></button></span></span>",
    "highlight": "I recently had the pleasure of working with...",
    "image": "fiver.svg",
    "country": "India",
    "date": "1 year ago"
  },
  {
    "client": "supertnt301281",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "It has been very good working with the seller they have delivered a quality website even though the backend isn't finished yet I can tell it what I was envisioning  there are few snagging problems but I have faith they will fix them by the end of part the backend",
    "highlight": "It has been very good working with the...",
    "image": "fiver.svg",
    "country": "United Kingdom",
    "date": "2 years ago"
  },
  {
    "client": "annourhamza",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "good seller, thank you",
    "highlight": "good seller, thank you...",
    "image": "fiver.svg",
    "country": "Morocco",
    "date": "1 year ago"
  },
  {
    "client": "reisponsive",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "We will definitely be using this gentleman again I highly recommend him",
    "highlight": "We will definitely be using this gentleman again...",
    "image": "fiver.svg",
    "country": "United States",
    "date": "2 years ago"
  },
  {
    "client": "wifidex",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "Work with professionalism and very good communication skills. I will definitely work with him since I have lots of projects. He over-delivered and work hard to finalize our projects. I am working on my projects and definitely having this guy remove lots of stress from my work. I am a Laravel Framework... <span class=\"expand-description-wrapper\"><span class=\"expand-button\"><button class=\"_05cff4 _15fd3a co-white expand-description expand-button-text bg-co-green-700\" data-impression-collected=\"true\"><span class=\"text-normal\"><u>See more</u></span></button></span></span>",
    "highlight": "Work with professionalism and very good communication skills....",
    "image": "fiver.svg",
    "country": "Canada",
    "date": "2 years ago"
  },
  {
    "client": "shashi_ccz",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "Excellent guy to work with. I will provide more work in the future.",
    "highlight": "Excellent guy to work with. I will provide...",
    "image": "fiver.svg",
    "country": "India",
    "date": "2 years ago"
  },
  {
    "client": "pulseblock",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "The seller was very easy to work with and very professional. He understood everything that needed to be done and went above and beyond to get it done!",
    "highlight": "The seller was very easy to work with...",
    "image": "fiver.svg",
    "country": "United States",
    "date": "2 years ago"
  },
  {
    "client": "nantaastic",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "This seller is very patient and super hardworking!! Great communication skills and very professional. I would totally recommend. I am very impressed and thankful. Thank you so much for all your hard work and dedication Adnan. Keep up the great work!",
    "highlight": "This seller is very patient and super hardworking!!...",
    "image": "fiver.svg",
    "country": "Tanzania",
    "date": "2 years ago"
  },
  {
    "client": "shawti12",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "unbelievable developer this guy is really good",
    "highlight": "unbelievable developer this guy is really good...",
    "image": "fiver.svg",
    "country": "United States",
    "date": "3 years ago"
  },
  {
    "client": "keshavbean",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "what an fruitful experience working with him..  Mr. Adnan listen very carefully for every task and understood it completely then deliver them beyond my exception. highly recommends him to others... He is your right Guy for every task!",
    "highlight": "what an fruitful experience working with him.. ...",
    "image": "fiver.svg",
    "country": "Malaysia",
    "date": "3 years ago"
  },
  {
    "client": "mahi82",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "Thanks for the quality work !!",
    "highlight": "Thanks for the quality work !!...",
    "image": "fiver.svg",
    "country": "India",
    "date": "3 years ago"
  },
  {
    "client": "bingowingo22",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "most reliable and helpful. sorts issues fast. my go to guy",
    "highlight": "most reliable and helpful. sorts issues fast. my...",
    "image": "fiver.svg",
    "country": "United Kingdom",
    "date": "3 years ago"
  },
  {
    "client": "codeyourbrain",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "I will recommend using him to anyone. Thank you Adnan for the great delivery.",
    "highlight": "I will recommend using him to anyone. Thank...",
    "image": "fiver.svg",
    "country": "Italy",
    "date": "3 years ago"
  },
  {
    "client": "sakibsaudagars",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "Placed an order to redesign our website. It looks great now!! thank you very much. He was very professional and patient in making all the changes we needed quick, good communication too, I highly recommend 👍",
    "highlight": "Placed an order to redesign our website. It...",
    "image": "fiver.svg",
    "country": "India",
    "date": "4 years ago"
  },
  {
    "client": "reiveram",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "I had a great experience working with this team, Great seller and very experienced in php. Had my job done in less than on time and it works perfectly. I strongly recommend this seller and will definitely be using him again.",
    "highlight": "I had a great experience working with this...",
    "image": "fiver.svg",
    "country": "India",
    "date": "3 years ago"
  },
  {
    "client": "nilaysaha1995",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "Very sincere, punctual and recommended. Great working with him, and will work more.",
    "highlight": "Very sincere, punctual and recommended. Great working with...",
    "image": "fiver.svg",
    "country": "India",
    "date": "4 years ago"
  },
  {
    "client": "ibd2004",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "Bad communication, always looking to squeeze more money and to present the task as more complicated than it is. Fill not honest at all. Too bad. I will not work with him again.",
    "highlight": "Bad communication, always looking to squeeze more money...",
    "image": "fiver.svg",
    "country": "Israel",
    "date": "4 years ago"
  },
  {
    "client": "hyp3fox",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "He did an amazing job! Quick, straightforward, and complete.",
    "highlight": "He did an amazing job! Quick, straightforward, and...",
    "image": "fiver.svg",
    "country": "United States",
    "date": "4 years ago"
  },
  {
    "client": "erikbilal",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "Makes a great site. I couldn't ask for better work. Will use again",
    "highlight": "Makes a great site. I couldn't ask for...",
    "image": "fiver.svg",
    "country": "United States",
    "date": "4 years ago"
  },
  {
    "client": "nightcypher",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "very good job",
    "highlight": "very good job...",
    "image": "fiver.svg",
    "country": "Malaysia",
    "date": "4 years ago"
  },
  {
    "client": "bwaystechsol",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "exceptional work!",
    "highlight": "exceptional work!...",
    "image": "fiver.svg",
    "country": "India",
    "date": "4 years ago"
  },
  {
    "client": "manousky",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "It's Adnan's winner attitude that stood out the most to me, despite the difficulty of the task I assigned him. No, he's no Einstein but he doesn't claim to be one either. But he knows to fight like hell and deliver what he promised. \n\nHe kept me updated on his progress at all times and even when things... <span class=\"expand-description-wrapper\"><span class=\"expand-button\"><button class=\"_05cff4 _15fd3a co-white expand-description expand-button-text bg-co-green-700\" data-impression-collected=\"true\"><span class=\"text-normal\"><u>See more</u></span></button></span></span>",
    "highlight": "It's Adnan's winner attitude that stood out the...",
    "image": "fiver.svg",
    "country": "Japan",
    "date": "4 years ago"
  },
  {
    "client": "yukeshwork",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "Very Good!",
    "highlight": "Very Good!...",
    "image": "fiver.svg",
    "country": "Nepal",
    "date": "4 years ago"
  },
  {
    "client": "malikirfanawan",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "He is fast and quick, a PHP developer with hands-on experience in all levels of fixing, including performance, functional, integration, etc. Will recommend working with him.",
    "highlight": "He is fast and quick, a PHP developer...",
    "image": "fiver.svg",
    "country": "Pakistan",
    "date": "4 years ago"
  },
  {
    "client": "yapp12",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "thank you thank you thank you thank you thank you",
    "highlight": "thank you thank you thank you thank you...",
    "image": "fiver.svg",
    "country": "Canada",
    "date": "4 years ago"
  },
  {
    "client": "dccyemen",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "Excellent and fast",
    "highlight": "Excellent and fast...",
    "image": "fiver.svg",
    "country": "Saudi Arabia",
    "date": "4 years ago"
  },
  {
    "client": "russellpearc892",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "absolutly prrfrct. great communucation  completed the job nice and quick. will be using again. Thanks rely good service",
    "highlight": "absolutly prrfrct. great communucation  completed the job...",
    "image": "fiver.svg",
    "country": "United Kingdom",
    "date": "4 years ago"
  },
  {
    "client": "socialsharingll",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "Perfect seller",
    "highlight": "Perfect seller...",
    "image": "fiver.svg",
    "country": "United States",
    "date": "4 years ago"
  },
  {
    "client": "mohsinabbas993",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "It was a great experience. This guy knows php very well and work efficiently and always come up with a solution. I will recommend him for his dedication, hardwork and patience. He follows command and do his work honestly. I will surely hire him again if I need help with something.",
    "highlight": "It was a great experience. This guy knows...",
    "image": "fiver.svg",
    "country": "Pakistan",
    "date": "4 years ago"
  },
  {
    "client": "shahnc",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "Very good communicator. Good job.",
    "highlight": "Very good communicator. Good job....",
    "image": "fiver.svg",
    "country": "Pakistan",
    "date": "4 years ago"
  },
  {
    "client": "wombseasons",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "He had communication skills",
    "highlight": "He had communication skills...",
    "image": "fiver.svg",
    "country": "United Kingdom",
    "date": "4 years ago"
  },
  {
    "client": "user82406355",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "Super great experience",
    "highlight": "Super great experience...",
    "image": "fiver.svg",
    "country": "France",
    "date": "4 years ago"
  },
  {
    "client": "cpufreezer",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "Excellent and quick work. Always responded right away and helped me a lot with my project!",
    "highlight": "Excellent and quick work. Always responded right away...",
    "image": "fiver.svg",
    "country": "Germany",
    "date": "4 years ago"
  },
  {
    "client": "kanvienter",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "great work and fast delivery",
    "highlight": "great work and fast delivery...",
    "image": "fiver.svg",
    "country": "India",
    "date": "4 years ago"
  },
  {
    "client": "dakshdatta",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "Very amazing and quick service. i appreciate the developer's creative mindset for helping me to improve the design for my website and being very punctual on time. Also communication was very good and he completed all minor tasks with accurate details. Would really recommend him for your future endeavors. I must say he is a really talented guy.",
    "highlight": "Very amazing and quick service. i appreciate the...",
    "image": "fiver.svg",
    "country": "India",
    "date": "4 years ago"
  },
  {
    "client": "michaelscriv854",
    "project": "Web Development",
    "stack": "Fiverr Order",
    "rating": 5,
    "quote": "I was very fortunate to have met Adnan. He is a gifted developer and a gifted designer. His work is of a high quality, he is very responsive, friendly, and great to work with. I will recommend using him to anyone. Thank you Adnan for the great delivery.",
    "highlight": "I was very fortunate to have met Adnan....",
    "image": "images/fiverr_logo_placeholder.png",
    "country": "Namibia",
    "date": "4 years ago"
  }
];
